name: Android CI/CD

on:
  push:
    branches:
      - release  # Укажите ветку, которую вы хотите отслеживать

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Upload APK to Google Play
        run: fastlane supply
        env:
          GOOGLE_PLAY_JSON_KEY: ${{ secrets.GOOGLE_PLAY_JSON_KEY }}
          PACKAGE_NAME: "io.eduonline.devrush.devrushlmsmultiplatform"